import { useState, useEffect, useCallback, useMemo } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Calendar } from "@/components/ui/calendar";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { CalendarIcon, Info } from "lucide-react";
import { ContactPickerIcon } from "@/components/contacts/ContactPickerIcon";
import { InternationalPhoneInput } from "@/components/phone/InternationalPhoneInput";
import { MessagePreview } from "./MessagePreview";
import { format, addMinutes } from "date-fns";
import { toZonedTime, fromZonedTime } from "date-fns-tz";
import { cn } from "@/lib/utils";
import { toast } from "@/hooks/use-toast";
import {
  InstructionKey,
  TimePresetKey,
  RepeatKey,
  INSTRUCTION_OPTIONS,
  TIME_PRESETS,
  REPEAT_OPTIONS,
  generateMedicationMessage,
  getDbFrequency,
} from "@/lib/medicationUtils";
import { ReminderInsert } from "@/hooks/useReminders";

type Voice = "friendly_female" | "friendly_male";

interface MedicationReminderFormProps {
  onSubmit: (reminders: Omit<ReminderInsert, "user_id">[]) => Promise<void>;
  isPending: boolean;
  defaultTimezone: string;
}

export const MedicationReminderForm = ({
  onSubmit,
  isPending,
  defaultTimezone,
}: MedicationReminderFormProps) => {
  // Get default date/time
  const getDefaultDateTime = useCallback(() => {
    const now = new Date();
    const oneMinuteFromNow = addMinutes(now, 1);
    const zonedTime = toZonedTime(oneMinuteFromNow, defaultTimezone);
    return {
      date: zonedTime,
      time: format(zonedTime, "HH:mm"),
    };
  }, [defaultTimezone]);

  const defaultDateTime = getDefaultDateTime();

  // Form state
  const [recipientName, setRecipientName] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");
  const [isPhoneValid, setIsPhoneValid] = useState(false);
  const [medicationName, setMedicationName] = useState("");
  const [dosage, setDosage] = useState("");
  const [instruction, setInstruction] = useState<InstructionKey>("none");
  const [timePreset, setTimePreset] = useState<TimePresetKey>("morning");
  const [customTime, setCustomTime] = useState(defaultDateTime.time);
  const [repeat, setRepeat] = useState<RepeatKey>("daily");
  const [date, setDate] = useState<Date | undefined>(defaultDateTime.date);
  const [voice, setVoice] = useState<Voice>("friendly_female");
  const [datePickerOpen, setDatePickerOpen] = useState(false);
  
  // Message state
  const [message, setMessage] = useState("");
  const [isManuallyEdited, setIsManuallyEdited] = useState(false);

  // Check if we're using multi-time repeat options
  const isMultiTime = repeat === "twice_daily" || repeat === "three_times_daily";

  // Auto-generated message
  const autoGeneratedMessage = useMemo(() => {
    return generateMedicationMessage(recipientName, medicationName, dosage, instruction);
  }, [recipientName, medicationName, dosage, instruction]);

  // Get the actual time to use
  const getSelectedTime = useCallback((): string => {
    if (timePreset === "custom") {
      return customTime;
    }
    const preset = TIME_PRESETS.find(p => p.key === timePreset);
    return preset?.time || "09:00";
  }, [timePreset, customTime]);

  const handlePhoneChange = (e164Value: string, isValid: boolean) => {
    setPhoneNumber(e164Value);
    setIsPhoneValid(isValid);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Validation
    if (recipientName.trim().length < 2) {
      toast({ title: "Recipient name must be at least 2 characters", variant: "destructive" });
      return;
    }

    if (!isPhoneValid || !phoneNumber) {
      toast({ title: "Please enter a valid phone number", variant: "destructive" });
      return;
    }

    if (!medicationName.trim()) {
      toast({ title: "Please enter the medication name", variant: "destructive" });
      return;
    }

    if (!date) {
      toast({ title: "Please select a date", variant: "destructive" });
      return;
    }

    if (!message.trim()) {
      toast({ title: "Message cannot be empty", variant: "destructive" });
      return;
    }

    const frequency = getDbFrequency(repeat);
    const repeatOption = REPEAT_OPTIONS.find(r => r.key === repeat);

    // Determine which times to create reminders for
    const timesToCreate = isMultiTime && repeatOption?.times 
      ? repeatOption.times 
      : [getSelectedTime()];

    // Create reminder objects
    const reminders: Omit<ReminderInsert, "user_id">[] = timesToCreate.map(time => {
      const [hours, minutes] = time.split(":").map(Number);
      const localDateTime = new Date(date);
      localDateTime.setHours(hours, minutes, 0, 0);
      
      // Convert from selected timezone to UTC
      const scheduledAt = fromZonedTime(localDateTime, defaultTimezone);

      return {
        recipient_name: recipientName.trim(),
        phone_number: phoneNumber,
        message: message.trim(),
        scheduled_at: scheduledAt.toISOString(),
        frequency,
        voice,
      };
    });

    // Validate at least one is in the future
    const now = new Date();
    const futureReminders = reminders.filter(r => new Date(r.scheduled_at) > now);
    
    if (futureReminders.length === 0) {
      toast({ title: "Scheduled time must be in the future", variant: "destructive" });
      return;
    }

    try {
      await onSubmit(futureReminders);
    } catch (error) {
      // Error handling is done in parent
    }
  };

  // Get start of today for calendar minimum date
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  return (
    <form onSubmit={handleSubmit} className="p-4 space-y-6">
      {/* Recipient Details */}
      <div className="bg-secondary/50 rounded-lg p-4 space-y-4">
        <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
          Who is this for?
        </p>
        <div className="space-y-2">
          <Label htmlFor="med-recipientName">Recipient Name</Label>
          <div className="relative">
            <Input
              id="med-recipientName"
              placeholder="e.g. Dad, Grandma"
              value={recipientName}
              onChange={(e) => setRecipientName(e.target.value)}
              className="pr-10"
            />
            <div className="absolute right-1 top-1/2 -translate-y-1/2">
              <ContactPickerIcon
                onSelect={(name, phone) => {
                  setRecipientName(name);
                  setPhoneNumber(phone);
                  setIsPhoneValid(true);
                }}
              />
            </div>
          </div>
        </div>
        <InternationalPhoneInput
          id="med-phoneNumber"
          value={phoneNumber}
          onChange={handlePhoneChange}
          label="Phone Number"
          showCostEstimate={true}
        />
      </div>

      {/* Medication Details */}
      <div className="bg-secondary/50 rounded-lg p-4 space-y-4">
        <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
          Medication Details
        </p>
        <div className="space-y-2">
          <Label htmlFor="medicationName">Medication Name *</Label>
          <Input
            id="medicationName"
            placeholder="e.g. Metformin, Blood pressure pills"
            value={medicationName}
            onChange={(e) => setMedicationName(e.target.value.slice(0, 100))}
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="dosage">Dosage (optional)</Label>
          <Input
            id="dosage"
            placeholder="e.g. 2 tablets, 10mg, 1 capsule"
            value={dosage}
            onChange={(e) => setDosage(e.target.value.slice(0, 50))}
          />
        </div>
        <div className="space-y-2">
          <Label>Instructions (optional)</Label>
          <Select value={instruction} onValueChange={(v) => setInstruction(v as InstructionKey)}>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select instructions" />
            </SelectTrigger>
            <SelectContent className="bg-popover">
              {INSTRUCTION_OPTIONS.map((opt) => (
                <SelectItem key={opt.key} value={opt.key}>
                  {opt.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>

      {/* Schedule */}
      <div className="bg-secondary/50 rounded-lg p-4 space-y-4">
        <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
          Schedule
        </p>
        
        {/* Date Picker */}
        <div className="space-y-2">
          <Label>Starting Date</Label>
          <Popover open={datePickerOpen} onOpenChange={setDatePickerOpen}>
            <PopoverTrigger asChild>
              <Button
                variant="outline"
                className={cn(
                  "w-full justify-start text-left font-normal",
                  !date && "text-muted-foreground"
                )}
              >
                <CalendarIcon className="mr-2 h-4 w-4" />
                {date ? format(date, "MMM d, yyyy") : "Pick a date"}
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-auto p-0" align="start">
              <Calendar
                mode="single"
                selected={date}
                onSelect={(selectedDate) => {
                  setDate(selectedDate);
                  setDatePickerOpen(false);
                }}
                disabled={(d) => d < today}
                initialFocus
                className="pointer-events-auto"
              />
            </PopoverContent>
          </Popover>
        </div>

        {/* Repeat Selection */}
        <div className="space-y-2">
          <Label>Repeat</Label>
          <Select value={repeat} onValueChange={(v) => setRepeat(v as RepeatKey)}>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select frequency" />
            </SelectTrigger>
            <SelectContent className="bg-popover">
              {REPEAT_OPTIONS.map((opt) => (
                <SelectItem key={opt.key} value={opt.key}>
                  {opt.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Time Selection - Show based on repeat type */}
        {isMultiTime ? (
          <div className="flex items-start gap-2 p-3 bg-primary/5 rounded-lg">
            <Info className="h-4 w-4 text-primary mt-0.5 flex-shrink-0" />
            <p className="text-sm text-muted-foreground">
              Reminders will be set for{" "}
              <span className="font-medium text-foreground">
                {REPEAT_OPTIONS.find(r => r.key === repeat)?.description}
              </span>
            </p>
          </div>
        ) : (
          <div className="space-y-2">
            <Label>When</Label>
            <Select value={timePreset} onValueChange={(v) => setTimePreset(v as TimePresetKey)}>
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select time" />
              </SelectTrigger>
              <SelectContent className="bg-popover">
                {TIME_PRESETS.map((preset) => (
                  <SelectItem key={preset.key} value={preset.key}>
                    {preset.key !== "custom" 
                      ? `${preset.label} (${format(new Date(`2000-01-01T${preset.time}`), "h:mm a")})`
                      : preset.label
                    }
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            
            {timePreset === "custom" && (
              <Input
                type="time"
                value={customTime}
                onChange={(e) => setCustomTime(e.target.value)}
                className="w-full"
              />
            )}
          </div>
        )}
      </div>

      {/* Message Preview */}
      <div className="bg-secondary/50 rounded-lg p-4 space-y-4">
        <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
          Call Script
        </p>
        <MessagePreview
          autoGeneratedMessage={autoGeneratedMessage}
          value={message}
          onChange={setMessage}
          isManuallyEdited={isManuallyEdited}
          onManualEdit={setIsManuallyEdited}
        />
      </div>

      {/* Voice Selection */}
      <div className="bg-secondary/50 rounded-lg p-4 space-y-4">
        <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
          Voice
        </p>
        <div className="grid grid-cols-2 gap-3">
          <button
            type="button"
            onClick={() => setVoice("friendly_female")}
            className={cn(
              "p-4 rounded-lg border-2 transition-all text-left",
              voice === "friendly_female"
                ? "border-primary bg-primary/5"
                : "border-border hover:border-primary/50"
            )}
          >
            <div className="w-10 h-10 rounded-full bg-gradient-to-br from-pink-200 to-purple-200 mb-2" />
            <p className="font-medium text-sm">Friendly Female</p>
            <p className="text-xs text-muted-foreground">Warm & Clear</p>
          </button>
          <button
            type="button"
            onClick={() => setVoice("friendly_male")}
            className={cn(
              "p-4 rounded-lg border-2 transition-all text-left",
              voice === "friendly_male"
                ? "border-primary bg-primary/5"
                : "border-border hover:border-primary/50"
            )}
          >
            <div className="w-10 h-10 rounded-full bg-gradient-to-br from-blue-200 to-cyan-200 mb-2" />
            <p className="font-medium text-sm">Friendly Male</p>
            <p className="text-xs text-muted-foreground">Calm & Professional</p>
          </button>
        </div>
      </div>

      {/* Spacer for sticky button */}
      <div className="h-20" />

      {/* Sticky Submit Button */}
      <div className="sticky bottom-0 left-0 right-0 p-4 -mx-4 -mb-4 bg-background border-t border-border">
        <Button
          type="submit"
          className="w-full h-12 text-base font-semibold"
          disabled={isPending}
        >
          {isPending ? "Creating..." : "Create Reminder"}
        </Button>
      </div>
    </form>
  );
};
