import { useState, useEffect } from "react";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Pencil, Info } from "lucide-react";

interface MessagePreviewProps {
  autoGeneratedMessage: string;
  value: string;
  onChange: (message: string) => void;
  isManuallyEdited: boolean;
  onManualEdit: (isManual: boolean) => void;
  medicationCount?: number;
}

export const MessagePreview = ({
  autoGeneratedMessage,
  value,
  onChange,
  isManuallyEdited,
  onManualEdit,
  medicationCount,
}: MessagePreviewProps) => {
  const [isEditing, setIsEditing] = useState(false);

  // Update message with auto-generated content when not manually edited
  useEffect(() => {
    if (!isManuallyEdited) {
      onChange(autoGeneratedMessage);
    }
  }, [autoGeneratedMessage, isManuallyEdited, onChange]);

  const handleEdit = () => {
    setIsEditing(true);
    onManualEdit(true);
  };

  const handleReset = () => {
    onChange(autoGeneratedMessage);
    onManualEdit(false);
    setIsEditing(false);
  };

  const handleChange = (newValue: string) => {
    onChange(newValue.slice(0, 500));
  };

  if (isEditing || isManuallyEdited) {
    return (
      <div className="space-y-2">
        <Label>Message</Label>
        <Textarea
          value={value}
          onChange={(e) => handleChange(e.target.value)}
          placeholder="Enter your reminder message..."
          className="min-h-[100px] resize-none"
        />
        <div className="flex justify-between items-center">
          <button
            type="button"
            onClick={handleReset}
            className="text-xs text-primary hover:text-primary/80 transition-colors"
          >
            Reset to auto
          </button>
          <span className="text-xs text-muted-foreground">{value.length}/500</span>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-2">
      <Label>Message Preview</Label>
      {medicationCount && medicationCount >= 3 && (
        <p className="text-xs text-muted-foreground flex items-center gap-1">
          <Info className="h-3 w-3" />
          {medicationCount >= 5 
            ? "Summary message for brevity" 
            : "Dosages included, instructions summarized"}
        </p>
      )}
      <div className="relative bg-secondary/30 rounded-xl p-4">
        <p className="text-sm leading-relaxed text-foreground pr-12">
          {value || "Fill in the details above to see your message..."}
        </p>
        <Button
          type="button"
          variant="ghost"
          size="sm"
          onClick={handleEdit}
          className="absolute bottom-2 right-2 h-8 text-xs text-muted-foreground hover:text-foreground"
        >
          <Pencil className="h-3 w-3 mr-1" />
          Edit
        </Button>
      </div>
    </div>
  );
};
